# Generated by Django 4.0.4 on 2022-08-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('school', models.CharField(max_length=300, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('field', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('idline', models.CharField(max_length=50, null=True)),
                ('identity', models.ImageField(upload_to='media')),
                ('payment', models.ImageField(upload_to='media')),
            ],
        ),
    ]
