# Generated by Django 4.0.4 on 2022-09-08 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=300, null=True)),
                ('school', models.CharField(max_length=300, null=True)),
                ('leader', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('docs', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='participant',
            name='field',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='idline',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='payment',
        ),
        migrations.AddField(
            model_name='participant',
            name='docs',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('grade', models.CharField(max_length=50, null=True)),
                ('phone', models.CharField(max_length=300, null=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regis.team')),
            ],
        ),
    ]
